# Generated by Django 4.2 on 2023-04-12 00:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('nickname', models.CharField(max_length=15)),
                ('avatar', models.ImageField(blank=True, upload_to='./static/avs')),
                ('reg_date', models.DateField(default=datetime.date(2023, 4, 12))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('creation_date', models.DateField(default=datetime.date(2023, 4, 12))),
                ('rating', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askPupkin_app.profile')),
                ('rated', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='askPupkin_app.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('correctness', models.BooleanField(default=False)),
                ('creation_date', models.DateField(default=datetime.date(2023, 4, 12))),
                ('rating', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askPupkin_app.profile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askPupkin_app.question')),
                ('rated', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
