# Generated by Django 4.2 on 2023-04-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askPupkin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
