# Generated by Django 4.2 on 2023-04-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askPupkin_app', '0002_alter_question_description_alter_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='viewed',
            field=models.IntegerField(default=0),
        ),
    ]
